
2023-11-03 11:25:13,592 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-03 11:25:13,593 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-03 11:25:13,596 - kivy - WARNING - LED BUTTON: GPIO module import error: No module named 'sensor_files'

2023-11-03 11:25:13,617 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f81c8fe7150>" was accessed, it will be removed in a future version

2023-11-03 11:25:16,966 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 21:24:06,736 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 21:24:06,737 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 21:24:06,758 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f20f4832b30>" was accessed, it will be removed in a future version

2023-11-06 21:24:10,138 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 21:26:26,776 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 21:26:26,777 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 21:26:26,799 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f1b1a57aac0>" was accessed, it will be removed in a future version

2023-11-06 21:26:30,168 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 21:27:39,150 - kivy - WARNING - stderr: Process Process-1:

2023-11-06 21:27:39,154 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,155 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-06 21:27:39,156 - kivy - WARNING - stderr:     self.run()

2023-11-06 21:27:39,156 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-06 21:27:39,157 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 21:27:39,157 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-06 21:27:39,158 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-06 21:27:39,158 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-06 21:27:39,159 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-06 21:27:39,159 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-06 21:27:39,159 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-06 21:27:39,159 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-06 21:27:39,160 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 21:27:39,160 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 21:27:39,276 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,277 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:     self.run_forever()

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:     self._run_once()

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:     handle._run()

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2023-11-06 21:27:39,278 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/interface_drivers/controller_template.py", line 52, in on_connect_default

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:     return await self.on_connect(*args, **kwargs)

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/interfaces.py", line 231, in _on_connect

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:     self.on_connect(self)

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/interface_factory.py", line 233, in on_connect

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:     self.external_on_connect(interface)

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/input_ouput.py", line 539, in connect_interface

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:     self.interfaces[interface.name] = interface

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 974, in kivy.properties.ObservableDict.__setitem__

2023-11-06 21:27:39,279 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 944, in kivy.properties.observable_dict_dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 625, in kivy.properties.Property.dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1189, in kivy._event.EventObservers._dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 67, in call_fn

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:     setattr(element, key, e_value)

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 939, in kivy.properties.ListProperty.set

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 567, in kivy.properties.Property.set

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1189, in kivy._event.EventObservers._dispatch

2023-11-06 21:27:39,280 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 55, in custom_callback

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:     exec(__kvlang__.co_value, idmap)

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "<string>", line 50, in <module>

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/screens/rec.py", line 425, in interface_disconnect

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:     self.toggle_interface(self.ids.interfacebutt.types[-1])

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/screens/rec.py", line 421, in toggle_interface

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:     self.app.IO.toggle_interface(interface)

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/input_ouput.py", line 550, in toggle_interface

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:     self._update_plot_pars()

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/input_ouput.py", line 402, in _update_plot_pars

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:     self.sensors.update(sensors)

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 1005, in kivy.properties.ObservableDict.update

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 944, in kivy.properties.observable_dict_dispatch

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 625, in kivy.properties.Property.dispatch

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch

2023-11-06 21:27:39,281 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/widgets/chips_widget.py", line 134, in create_buttons

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:     self.chip_labels = {name: ChipLabel(self.app.IO.sensors[name], name, self.app, self) 

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/widgets/chips_widget.py", line 134, in <dictcomp>

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:     self.chip_labels = {name: ChipLabel(self.app.IO.sensors[name], name, self.app, self) 

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/widgets/chips_widget.py", line 80, in __init__

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:     default_opts = chip.return_default_options()

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:                    ^^^^

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/widgets/chips_widget.py", line 80, in __init__

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:     default_opts = chip.return_default_options()

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:                    ^^^^

2023-11-06 21:27:39,282 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch

2023-11-06 21:27:39,291 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg)

2023-11-06 21:27:39,291 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-06 21:27:39,292 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 21:27:39,292 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 21:27:39,292 - kivy - WARNING - stderr: 

2023-11-06 21:27:39,292 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 21:27:39,293 - kivy - WARNING - stderr: 

2023-11-06 21:27:39,293 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:     cli.main()

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:     run()

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,293 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     self.close()

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     self.run_forever()

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     self._run_once()

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-06 21:27:39,294 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-06 21:27:39,295 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,295 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-06 21:27:39,295 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-06 21:27:39,295 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,295 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 21:27:39,443 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-06 21:27:39,444 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-7 (_do_shutdown):

2023-11-06 21:27:39,444 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,444 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,445 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-06 21:27:39,445 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-06 21:27:39,445 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-06 21:27:39,445 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 21:27:39,446 - kivy - WARNING - stderr:     atexit_call()

2023-11-06 21:27:39,446 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-06 21:27:39,446 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 21:27:39,447 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 21:27:39,447 - kivy - WARNING - stderr:     t.join()

2023-11-06 21:27:39,447 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-06 21:27:39,447 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 21:27:39,447 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 21:27:39,447 - kivy - WARNING - stderr: 

2023-11-06 21:27:39,448 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-06 21:27:39,448 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 21:27:39,448 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-06 21:27:39,448 - kivy - WARNING - stderr: 

2023-11-06 21:27:39,448 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2023-11-06 21:27:39,449 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,449 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 21:27:39,449 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-06 21:27:39,449 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-06 21:27:39,450 - kivy - WARNING - stderr:     self.run()

2023-11-06 21:27:39,450 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-06 21:27:39,451 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 21:27:39,451 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-06 21:27:39,451 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-06 21:27:39,451 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 21:27:39,451 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 21:27:39,452 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 21:27:39,452 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 21:27:39,452 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 21:27:39,597 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 21:27:39,598 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-06 21:27:39,598 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-06 21:27:39,598 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:24:31,049 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:24:31,049 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:24:31,071 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fc228166ba0>" was accessed, it will be removed in a future version

2023-11-06 22:24:34,442 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:34:48,389 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:34:48,389 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:34:48,411 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f41cd976a50>" was accessed, it will be removed in a future version

2023-11-06 22:34:51,784 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:36:12,176 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,176 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-06 22:36:12,177 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-06 22:36:12,177 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,177 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete

2023-11-06 22:36:12,177 - kivy - WARNING - stderr: Process Process-1:

2023-11-06 22:36:12,178 - kivy - WARNING - stderr:     return future.result()

2023-11-06 22:36:12,178 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^

2023-11-06 22:36:12,178 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-06 22:36:12,178 - kivy - WARNING - stderr:     await app.async_run()

2023-11-06 22:36:12,178 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-06 22:36:12,179 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-06 22:36:12,179 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-06 22:36:12,180 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-06 22:36:12,180 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,180 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-06 22:36:12,180 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-06 22:36:12,180 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 418, in async_idle

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:     await Clock.async_tick()

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/clock.py", line 739, in async_tick

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:     self.run()

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:     current = await self.async_idle()

2023-11-06 22:36:12,181 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:               ^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/clock.py", line 710, in async_idle

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:     await self._async_lib.sleep(sleeptime)

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/tasks.py", line 644, in sleep

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:     return await future

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:            ^^^^^^^^^^^^

2023-11-06 22:36:12,182 - kivy - WARNING - stderr: asyncio.exceptions.CancelledError

2023-11-06 22:36:12,182 - kivy - WARNING - stderr: 

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:36:12,182 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: 

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: 

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: 

2023-11-06 22:36:12,183 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,183 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:     cli.main()

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-06 22:36:12,184 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:     run()

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-06 22:36:12,184 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:     self.close()

2023-11-06 22:36:12,185 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:     self.run_forever()

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:     self._run_once()

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,186 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-06 22:36:12,187 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-06 22:36:12,187 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,187 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:36:12,345 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-06 22:36:12,346 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-6 (_do_shutdown):

2023-11-06 22:36:12,346 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,348 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,348 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-06 22:36:12,349 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-06 22:36:12,352 - kivy - WARNING - stderr:     atexit_call()

2023-11-06 22:36:12,352 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-06 22:36:12,353 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-06 22:36:12,353 - kivy - WARNING - stderr:     t.join()

2023-11-06 22:36:12,353 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 22:36:12,353 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-06 22:36:12,353 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 22:36:12,353 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 22:36:12,354 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-06 22:36:12,354 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-06 22:36:12,354 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 22:36:12,354 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 22:36:12,354 - kivy - WARNING - stderr: RuntimeError: Event loop is closed    if lock.acquire(block, timeout):

2023-11-06 22:36:12,354 - kivy - WARNING - stderr: 

2023-11-06 22:36:12,354 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:36:12,354 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:36:12,354 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-06 22:36:12,354 - kivy - WARNING - stderr: 

2023-11-06 22:36:12,355 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:36:12,355 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-06 22:36:12,355 - kivy - WARNING - stderr:     self.run()

2023-11-06 22:36:12,356 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-06 22:36:12,357 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 22:36:12,357 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-06 22:36:12,358 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-06 22:36:12,358 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 22:36:12,358 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 22:36:12,358 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 22:36:12,358 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 22:36:12,358 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 22:36:51,171 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:36:51,172 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:36:51,195 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f291fb42ac0>" was accessed, it will be removed in a future version

2023-11-06 22:36:54,573 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:39:19,626 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:39:19,626 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:39:19,648 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f86d8622a50>" was accessed, it will be removed in a future version

2023-11-06 22:39:23,011 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:40:10,408 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:40:10,409 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:40:10,432 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f7b38506a50>" was accessed, it will be removed in a future version

2023-11-06 22:40:13,802 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:40:24,152 - kivy - WARNING - INPUT_OUTPUT: Parameter not in memory or no data yet: 'Not Connected'

2023-11-06 22:40:24,153 - kivy - WARNING - INPUT_OUTPUT: Parameter not in memory or no data yet: 'Not Connected'

2023-11-06 22:40:25,168 - kivy - WARNING - INPUT_OUTPUT: Parameter not in memory or no data yet: 'Not Connected'

2023-11-06 22:40:25,168 - kivy - WARNING - INPUT_OUTPUT: Parameter not in memory or no data yet: 'Not Connected'

2023-11-06 22:40:26,183 - kivy - WARNING - INPUT_OUTPUT: Parameter not in memory or no data yet: 'Not Connected'

2023-11-06 22:40:26,183 - kivy - WARNING - INPUT_OUTPUT: Parameter not in memory or no data yet: 'Not Connected'

2023-11-06 22:41:53,796 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:42:03,575 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:42:03,612 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f697efd2430>" was accessed, it will be removed in a future version

2023-11-06 22:42:06,997 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:44:02,528 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:44:05,238 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:44:05,271 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f44653ce3c0>" was accessed, it will be removed in a future version

2023-11-06 22:44:08,655 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:47:19,498 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:47:20,827 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:47:20,862 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fa4e5dde510>" was accessed, it will be removed in a future version

2023-11-06 22:47:24,252 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:51:52,642 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:51:52,643 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:51:52,666 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7efc428669e0>" was accessed, it will be removed in a future version

2023-11-06 22:51:56,052 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:52:12,972 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:12,973 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-06 22:52:12,972 - kivy - WARNING - stderr: Process Process-1:

2023-11-06 22:52:12,973 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-06 22:52:12,973 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,973 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete

2023-11-06 22:52:12,974 - kivy - WARNING - stderr:     return future.result()

2023-11-06 22:52:12,974 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^

2023-11-06 22:52:12,974 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-06 22:52:12,975 - kivy - WARNING - stderr:     await app.async_run()

2023-11-06 22:52:12,975 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-06 22:52:12,975 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:12,975 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-06 22:52:12,975 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-06 22:52:12,976 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-06 22:52:12,976 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-06 22:52:12,976 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-06 22:52:12,976 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-06 22:52:12,977 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 418, in async_idle

2023-11-06 22:52:12,977 - kivy - WARNING - stderr:     self.run()

2023-11-06 22:52:12,977 - kivy - WARNING - stderr:     await Clock.async_tick()

2023-11-06 22:52:12,977 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-06 22:52:12,977 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/clock.py", line 739, in async_tick

2023-11-06 22:52:12,977 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:     current = await self.async_idle()

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:               ^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/clock.py", line 710, in async_idle

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-06 22:52:12,978 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:     await self._async_lib.sleep(sleeptime)

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/tasks.py", line 644, in sleep

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:     return await future

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 22:52:12,979 - kivy - WARNING - stderr:            ^^^^^^^^^^^^

2023-11-06 22:52:12,979 - kivy - WARNING - stderr: asyncio.exceptions.CancelledError

2023-11-06 22:52:12,979 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:52:12,979 - kivy - WARNING - stderr: 

2023-11-06 22:52:12,979 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: 

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: 

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: 

2023-11-06 22:52:12,980 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-06 22:52:12,980 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:     cli.main()

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:     run()

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-06 22:52:12,981 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-06 22:52:12,982 - kivy - WARNING - stderr:     self.close()

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:     self.run_forever()

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:     self._run_once()

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-06 22:52:12,983 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-06 22:52:12,984 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,984 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-06 22:52:12,984 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-06 22:52:12,984 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:12,984 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:52:13,381 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-06 22:52:13,382 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-6 (_do_shutdown):

2023-11-06 22:52:13,382 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:13,383 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:13,383 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-06 22:52:13,384 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-06 22:52:13,386 - kivy - WARNING - stderr:     atexit_call()

2023-11-06 22:52:13,386 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-06 22:52:13,387 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 22:52:13,388 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 22:52:13,388 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-06 22:52:13,388 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 22:52:13,389 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 22:52:13,390 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 22:52:13,390 - kivy - WARNING - stderr: RuntimeError: Event loop is closed    t.join()

2023-11-06 22:52:13,390 - kivy - WARNING - stderr: 

2023-11-06 22:52:13,391 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-06 22:52:13,391 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:52:13,391 - kivy - WARNING - stderr: 

2023-11-06 22:52:13,392 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-06 22:52:13,392 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:13,392 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-06 22:52:13,392 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-06 22:52:13,393 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2023-11-06 22:52:13,393 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):    self.run()

2023-11-06 22:52:13,393 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:52:13,394 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-06 22:52:13,394 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-06 22:52:13,395 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 22:52:13,395 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-06 22:52:13,396 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-06 22:52:13,396 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 22:52:13,397 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 22:52:13,397 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 22:52:13,398 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 22:52:13,398 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 22:52:13,537 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:52:13,537 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-06 22:52:13,538 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-06 22:52:13,538 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:52:20,817 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:52:20,817 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:52:20,840 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fc14b66aac0>" was accessed, it will be removed in a future version

2023-11-06 22:52:24,237 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:53:03,871 - kivy - WARNING - VIDEO WIDGET: Unable to load camera: No module named 'picamera'

2023-11-06 22:53:03,871 - kivy - WARNING - VIDEO WIDGET: Cannot load H264 decoder, is Gstreamer installed? No module named 'gi'

2023-11-06 22:53:03,894 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f6ffd15a9e0>" was accessed, it will be removed in a future version

2023-11-06 22:53:07,312 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 22:53:14,097 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,097 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-06 22:53:14,097 - kivy - WARNING - stderr: Process Process-1:

2023-11-06 22:53:14,098 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-06 22:53:14,098 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,099 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete

2023-11-06 22:53:14,099 - kivy - WARNING - stderr:     return future.result()

2023-11-06 22:53:14,099 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^

2023-11-06 22:53:14,100 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-06 22:53:14,100 - kivy - WARNING - stderr:     await app.async_run()

2023-11-06 22:53:14,100 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-06 22:53:14,101 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,101 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-06 22:53:14,101 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-06 22:53:14,102 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-06 22:53:14,102 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-06 22:53:14,102 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-06 22:53:14,102 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-06 22:53:14,103 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 418, in async_idle

2023-11-06 22:53:14,103 - kivy - WARNING - stderr:     self.run()

2023-11-06 22:53:14,103 - kivy - WARNING - stderr:     await Clock.async_tick()

2023-11-06 22:53:14,103 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-06 22:53:14,103 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/clock.py", line 739, in async_tick

2023-11-06 22:53:14,103 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:     current = await self.async_idle()

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:               ^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/clock.py", line 710, in async_idle

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 22:53:14,104 - kivy - WARNING - stderr:     await self._async_lib.sleep(sleeptime)

2023-11-06 22:53:14,105 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/tasks.py", line 644, in sleep

2023-11-06 22:53:14,105 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:53:14,105 - kivy - WARNING - stderr:     return await future

2023-11-06 22:53:14,105 - kivy - WARNING - stderr:            ^^^^^^^^^^^^

2023-11-06 22:53:14,105 - kivy - WARNING - stderr: asyncio.exceptions.CancelledError

2023-11-06 22:53:14,105 - kivy - WARNING - stderr: 

2023-11-06 22:53:14,105 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:53:14,105 - kivy - WARNING - stderr: 

2023-11-06 22:53:14,105 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,105 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-06 22:53:14,105 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-06 22:53:14,105 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-06 22:53:14,106 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:53:14,106 - kivy - WARNING - stderr: 

2023-11-06 22:53:14,106 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:53:14,106 - kivy - WARNING - stderr: 

2023-11-06 22:53:14,106 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-06 22:53:14,106 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:     cli.main()

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:     run()

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,107 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:     self.close()

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-06 22:53:14,108 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-06 22:53:14,109 - kivy - WARNING - stderr:     self.run_forever()

2023-11-06 22:53:14,109 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-06 22:53:14,109 - kivy - WARNING - stderr:     self._run_once()

2023-11-06 22:53:14,109 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-06 22:53:14,109 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-06 22:53:14,110 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,110 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-06 22:53:14,110 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-06 22:53:14,110 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,110 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:53:14,265 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-06 22:53:14,265 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-6 (_do_shutdown):

2023-11-06 22:53:14,266 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,267 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,267 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-06 22:53:14,268 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-06 22:53:14,269 - kivy - WARNING - stderr:     atexit_call()

2023-11-06 22:53:14,269 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-06 22:53:14,270 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-06 22:53:14,270 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 22:53:14,270 - kivy - WARNING - stderr:     t.join()

2023-11-06 22:53:14,271 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-06 22:53:14,272 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 22:53:14,272 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-06 22:53:14,272 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 22:53:14,273 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-06 22:53:14,273 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 22:53:14,273 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 22:53:14,274 - kivy - WARNING - stderr: 

2023-11-06 22:53:14,274 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-06 22:53:14,274 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2023-11-06 22:53:14,274 - kivy - WARNING - stderr: 

2023-11-06 22:53:14,275 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,275 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:53:14,275 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-06 22:53:14,275 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-06 22:53:14,276 - kivy - WARNING - stderr: KeyboardInterrupt:     self.run()

2023-11-06 22:53:14,276 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-06 22:53:14,278 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-06 22:53:14,278 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-06 22:53:14,278 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-06 22:53:14,279 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-06 22:53:14,279 - kivy - WARNING - stderr:     self._check_closed()

2023-11-06 22:53:14,279 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-06 22:53:14,280 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-06 22:53:14,280 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-06 22:53:14,435 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:53:14,436 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-06 22:53:14,436 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-06 22:53:14,436 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:55:14,316 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:55:14,318 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-06 22:55:14,318 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-06 22:55:14,318 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-06 22:55:14,318 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-06 22:55:14,318 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-06 22:55:14,318 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-06 22:55:14,319 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:55:14,319 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-06 22:55:14,319 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-06 22:55:14,319 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:55:14,520 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:55:14,520 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-06 22:55:14,521 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:55:14,521 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:55:14,521 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-06 22:55:14,521 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:55:14,522 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-06 22:55:14,522 - kivy - WARNING - stderr:     cli.main()

2023-11-06 22:55:14,522 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-06 22:55:14,522 - kivy - WARNING - stderr:     run()

2023-11-06 22:55:14,522 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-06 22:55:14,523 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-06 22:55:14,523 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-06 22:55:14,523 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-06 22:55:14,523 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:55:14,523 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-06 22:55:14,523 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-06 22:55:14,524 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 93, in <module>

2023-11-06 22:55:14,524 - kivy - WARNING - stderr:     from subs.gui.screens.root_layout import RootLayout

2023-11-06 22:55:14,524 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/gui/screens/root_layout.py", line 36, in <module>

2023-11-06 22:55:14,524 - kivy - WARNING - stderr:     from subs.video.videowidget import VideoDisplay

2023-11-06 22:55:14,524 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/video/videowidget.py", line 37, in <module>

2023-11-06 22:55:14,524 - kivy - WARNING - stderr:     from subs.video.videoprocessing import VideoProcessing

2023-11-06 22:55:14,525 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 204, in trace_dispatch

2023-11-06 22:55:14,533 - kivy - WARNING - stderr:     return thread_trace_func(frame, event, arg)

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 440, in __call__

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:     ).trace_dispatch(frame, event, arg)

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg)

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-06 22:55:14,534 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-06 22:55:14,535 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-06 22:55:14,535 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-06 22:55:14,535 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-06 22:55:14,535 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-06 22:55:14,535 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 22:55:14,686 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-06 22:55:14,687 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:55:14,687 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown

2023-11-06 22:55:14,688 - kivy - WARNING - stderr:     lock.acquire()

2023-11-06 22:55:14,688 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-06 22:55:14,864 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-06 22:55:14,864 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-06 22:55:14,864 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-06 22:55:14,864 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-06 23:00:30,991 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f593a265e10>" was accessed, it will be removed in a future version

2023-11-06 23:00:34,359 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-06 23:01:06,038 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f7dab55dda0>" was accessed, it will be removed in a future version

2023-11-06 23:01:09,411 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
